# Generated by Django 6.0.1 on 2026-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_user_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
